### ISSUE TITLE
Incorrect crc8

### ISSUE THREAD

**Issue by flowbish** [flowbish/cs439-audio#2]
For the packet "Hi Robin!!", the transmitter claims to send a crc of 0xc6, but the transmitter receives 0xfe. Since the receiver get all other bits correctly, this is most likely some bug in the transmission code.

**Comment by patrick0606** [comment]
My testing shows that the function itself works fine.
![2015-10-23 19_57_28](https://cloud.githubusercontent.com/assets/7421047/10708012/6cd9ce24-79c0-11e5-84b3-15c1c7c98e82.png)
But I have a question about line 129 in your main.cpp. Why does the iteration run (PACKET_LEN+1) times instead of PACKET_LEN times?

**Comment by flowbish** [comment]
Fixed by commit ddf8c54.
